name: Badminton Court Booking

# Run on Friday, Saturday, Sunday, Monday, Tuesday, and Thursday
on:
  schedule:
      - cron: '0 6-18/2 * * 1,2,4,5,6,0'  # Monday (1), Tuesday (2), Thursday (4), Friday (5), Saturday (6), Sunday (0)
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  book_badminton:
    name: Check for available badminton courts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
      
      - name: Run badminton booker script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NEIGHBORHOODS: ${{ secrets.NEIGHBORHOODS }}
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
        run: |
          python book.py --headless -test