name: Badminton Court Booking

on:
  schedule:
      - cron: '0 13,17,21,1 * * *'  # 8AM, 12PM, 4PM, 8PM EST (13:00, 17:00, 21:00, 01:00 UTC)
  workflow_dispatch:

jobs:
  book_badminton:
    name: Check for available badminton courts
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium    
      - name: Setup Firebase Certificate
        run: |
          echo "Setting up Firebase certificate"
          echo "${{ secrets.FIREBASE_CERTIFICATE_VALUE }}" | base64 --decode > badminton_booker/datastore/firebase_certificate.json
      - name: Run badminton booker script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NEIGHBORHOODS: ${{ secrets.NEIGHBORHOODS }}
          BOOKING_URL: ${{ secrets.BOOKING_URL }}
          FIREBASE_CERT_PATH: badminton_booker/datastore/firebase_certificate.json
        run: |
          python main.py --headless
