name: Update Chat IDs

on:
  schedule:
      - cron: '0 5 * * *'  # Once a day at Midnight EST (5 AM UTC)
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update_chat_ids:
    name: Check for any new chat IDs
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot python-dotenv firebase-admin
      - name: Setup Firebase Certificate
        run: |
          echo "Setting up Firebase certificate"
          echo "${{ secrets.FIREBASE_CERTIFICATE_VALUE }}" | base64 --decode > badminton_booker/datastore/firebase_certificate.json

      - name: Run Update Chat IDs script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FIREBASE_CERT_PATH: badminton_booker/datastore/firebase_certificate.json
        run: |
          python badminton_booker/datastore/chat_id_service.py